// Code generated by "stringer -type Code -linecomment -output code_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultDBCode-3000]
	_ = x[DefaultRequestCode-4000]
	_ = x[DefaultServerError-5000]
	_ = x[DefaultOtherServerCode-6000]
}

const (
	_Code_name_0 = "服务器开小差了，请重试"
	_Code_name_1 = "参数错误，请重试"
	_Code_name_2 = "服务器开小差了，请重试"
	_Code_name_3 = "服务器开小差了，请重试"
)

func (i Code) String() string {
	switch {
	case i == 3000:
		return _Code_name_0
	case i == 4000:
		return _Code_name_1
	case i == 5000:
		return _Code_name_2
	case i == 6000:
		return _Code_name_3
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
